### ISSUE TITLE
BUG: elementos do menu renderizam fora do contêiner

### ISSUE THREAD

**Issue by nawarian** [tecMTST/aventuras-sampa#115]
## Descrição do problema

Ao acionar o menu no feed de notícias, os botões e sliders aparecem fora do container principal.

## Como reproduzir

1. Iniciar o jogo, chegar até o feed de notícias
1. Clicar no botão de menu, ao lado do logo
1. Verificar o contêiner com os botões e sliders

### Vídeo / Imagem

Desktop:
![image](https://github.com/user-attachments/assets/f5b4c3f3-c39e-4505-a450-bc2256e0fb4f)

Mobile view:
![image](https://github.com/user-attachments/assets/2144eaa4-0f80-4c2d-a401-69973866d46d)

Mobile (android) o bug não acontece:
![image](https://github.com/user-attachments/assets/f38440ce-c1b6-4f11-b404-6779c9a73e0f)

## Comportamento esperado

Os botões e sliders devem aparecer dentro da imagem do contêiner.

## Plataformas

O teste foi realizado nestas plataformas:

* [ ] Windows /	Google Chrome
* [ ] Windows	/ Firefox
* [ ] Windows	/ Microsoft Edge
* [x] Linux	/ Google Chrome ou Chromium
* [x] Linux / Firefox
* [ ] Android	/ Firefox
* [x] Android /	Google Chrome - bug não acontece aqui
* [ ] Android	/ apk nativo
* [ ] iOS	/ Google Chrome
* [ ] iOS	/ Safari
* [ ] Mac	/ Google Chrome
* [ ] Mac	/ Safari

## Notas / Referências / Sugestões

(opcional) Adicionar aqui links, comentários ou sugestões.

**Comment by ClockWritesDev** [comment]
receio que isso seja problema nesse expand do viewport.

**Comment by mihailov-vf** [comment]
Com a remoção do feed, este bug não é mais significativo
