### ISSUE TITLE
BUG: feed não guarda quais notícias foram curtidas

### ISSUE THREAD

**Issue by nawarian** [tecMTST/aventuras-sampa#117]
## Descrição do problema

Quando se "curte" uma notícia no feed e inicia-se um jogo, ao retornar ao feed a curtida desaparece.

## Como reproduzir

1. Iniciar o jogo, visualizar o feed de notícias
1. Curtir uma notícia do feed
1. Iniciar um jogo e jogar até voltar ao feed de notícias
2. Verificar, no feed de notícias, que a notícia curtida já não está mais marcada como "curtida"

### Vídeo / Imagem

https://github.com/user-attachments/assets/3b24f037-c66d-4b0e-91b5-46e46a65822a

## Comportamento esperado

Ao curtir uma notícia o jogo deve lembrar-se daquela decisão e manter marcado
o botão curtir quando a pessoa jogadora retorna ao feed.

## Plataformas

O teste foi realizado nestas plataformas:

* [ ] Windows /	Google Chrome
* [ ] Windows	/ Firefox
* [ ] Windows	/ Microsoft Edge
* [x] Linux	/ Google Chrome ou Chromium
* [x] Linux / Firefox
* [ ] Android	/ Firefox
* [ ] Android /	Google Chrome
* [ ] Android	/ apk nativo
* [ ] iOS	/ Google Chrome
* [ ] iOS	/ Safari
* [ ] Mac	/ Google Chrome
* [ ] Mac	/ Safari

## Notas / Referências / Sugestões

(opcional) Adicionar aqui links, comentários ou sugestões.

**Comment by rodigu** [comment]
#129
