### ISSUE TITLE
BUG: segurar o botão de abaixar não faz efeito

### ISSUE THREAD

**Issue by nawarian** [tecMTST/aventuras-sampa#118]
## Descrição do problema

Ao pressionar a seta para baixo, a personagem se abaixa.

Manter a seta pressionada não faz com que a personagem se mantenha abaixada.

## Como reproduzir

1. Inicie o jogo
1. Pressione e mantenha pressionada a seta para baixo
1. Observe a personagem abaixar-se
2. Observe que após certo tempo ela se levanta automaticamente

### Vídeo / Imagem

https://github.com/user-attachments/assets/09725a2e-3ecc-40da-984a-6f6947fff544

## Comportamento esperado

* Ao manter pressionada a tecla, personagem mantém-se abaixada
* O intervalo entre mover-se e abaixar-se tem de ser menor

## Plataformas

O teste foi realizado nestas plataformas:

* [ ] Windows /	Google Chrome
* [ ] Windows	/ Firefox
* [ ] Windows	/ Microsoft Edge
* [x] Linux	/ Google Chrome ou Chromium
* [x] Linux / Firefox
* [ ] Android	/ Firefox
* [ ] Android /	Google Chrome
* [ ] Android	/ apk nativo
* [ ] iOS	/ Google Chrome
* [ ] iOS	/ Safari
* [ ] Mac	/ Google Chrome
* [ ] Mac	/ Safari

## Notas / Referências / Sugestões

(opcional) Adicionar aqui links, comentários ou sugestões.

**Comment by rodigu** [comment]
eu acho que era works as intended

**Comment by Kelvysb** [comment]
Sobre este Bug, devido as limitações do controle de deslizar, devemos discutir sobre o comando de agachar ser temporário, ver bug: https://github.com/tecMTST/aventuras-sampa/issues/139, e também sobre uma colocação feita sobre o jogador abusar da mecânica de se abaixar, mantendo pressionado o tempo todo.
