### ISSUE TITLE
BUG: logo desapareceu do feed

### ISSUE THREAD

**Issue by nawarian** [tecMTST/aventuras-sampa#135]
## Descrição do problema

A tela do feed deveria mostrar o logo do jogo bem ao topo. O espaço agora está vazio.

## Como reproduzir

1. Acessar o feed de notícias
2. Verifique que o logo desapareceu

### Vídeo / Imagem

![image](https://github.com/user-attachments/assets/675d5748-8dbc-4990-ae53-91650edda466)

## Comportamento esperado

O logo do jogo deveria aparecer ao topo da tela, antes de todas as notícias.

## Plataformas

O teste foi realizado nestas plataformas:

* [ ] Windows /	Google Chrome
* [ ] Windows	/ Firefox
* [ ] Windows	/ Microsoft Edge
* [ ] Linux	/ Google Chrome ou Chromium
* [x] Linux / Firefox
* [ ] Android	/ Firefox
* [x] Android /	Google Chrome
* [ ] Android	/ apk nativo
* [ ] iOS	/ Google Chrome
* [ ] iOS	/ Safari
* [ ] Mac	/ Google Chrome
* [ ] Mac	/ Safari

## Notas / Referências / Sugestões

(opcional) Adicionar aqui links, comentários ou sugestões.

**Comment by mihailov-vf** [comment]
Com a remoção do feed, este bug não é mais significativo
