### ISSUE TITLE
BUG: botão de comentário não faz nada

### ISSUE THREAD

**Issue by nawarian** [tecMTST/aventuras-sampa#136]
## Descrição do problema

Para cada notícia existe um ícone que é um balão de comentário. Ele não aparenta ter função nenhuma.

## Como reproduzir

1. Acessar o feed
1. Selecionar a primeira notícia
1. Clicar no balão de comentário
1. Observar que não aconteceu nada

### Vídeo / Imagem

![image](https://github.com/user-attachments/assets/acc88ac2-d7c1-47a1-9837-36a0fd55481b)

## Comportamento esperado

Se o botão não faz nada, melhor remover da tela.

## Plataformas

O teste foi realizado nestas plataformas:

* [ ] Windows /	Google Chrome
* [ ] Windows	/ Firefox
* [ ] Windows	/ Microsoft Edge
* [x] Linux	/ Google Chrome ou Chromium
* [ ] Linux / Firefox
* [x] Android	/ Firefox
* [ ] Android /	Google Chrome
* [ ] Android	/ apk nativo
* [ ] iOS	/ Google Chrome
* [ ] iOS	/ Safari
* [ ] Mac	/ Google Chrome
* [ ] Mac	/ Safari

## Notas / Referências / Sugestões

(opcional) Adicionar aqui links, comentários ou sugestões.

**Comment by mihailov-vf** [comment]
Com a remoção do feed, este bug não é mais significativo
