### ISSUE TITLE
Controle Touch

### ISSUE THREAD

**Issue by rodigu** [tecMTST/aventuras-sampa#16]
Funcao de pegar historico ao inves de eventos separados todo process

**Comment by ClockWritesDev** [comment]
### Fiz uma função que guarda o input recebido no historico e só é guardado quando houver um input na tela então ele não é ativado pela função de processo delta.
![Captura de tela_2024-06-05_14-15-03](https://github.com/tecMTST/aventuras-sampa/assets/99129331/1bd05dcf-64c0-4993-a578-8796949c9917)
