### ISSUE TITLE
BUG: aumentar velocidade no json nao aumenta velocidade no jogo

### ISSUE THREAD

**Issue by rodigu** [tecMTST/aventuras-sampa#169]
## Descrição do problema

Explicar em detalhes o mau comportamento do jogo.

## Como reproduzir

1. Passo
1. a
1. passo

### Vídeo / Imagem

...

## Comportamento esperado

Explicar em detalhes o comportamento adequado. Utilizar listas se necessário

## Plataformas

O teste foi realizado nestas plataformas:

* [ ] Windows /	Google Chrome
* [ ] Windows	/ Firefox
* [ ] Windows	/ Microsoft Edge
* [ ] Linux	/ Google Chrome ou Chromium
* [ ] Linux / Firefox
* [ ] Android	/ Firefox
* [ ] Android /	Google Chrome
* [ ] Android	/ apk nativo
* [ ] iOS	/ Google Chrome
* [ ] iOS	/ Safari
* [ ] Mac	/ Google Chrome
* [ ] Mac	/ Safari

## Notas / Referências / Sugestões

(opcional) Adicionar aqui links, comentários ou sugestões.

**Comment by mihailov-vf** [comment]
No PR #174 há um ajuste que corrige o problema de alterar o valor da velocidade, no entanto aparecem outros problemas.

- A cada troca de velocidade pode gerar um engasgo no shader
- Em velocidade 1.5 o pulo deixa de funcionar com a rampa
